---
title: "Video abstracts: What? Why? How?"
authors: admin
date: "2020-08-19"
number_sections: false
codefolding_nobutton: false
disable_codefolding: true
slug: 
bibliography: 
link-citations: true
categories: []
tags:
  - video abstracts
  - thermostatically-controlled loads
header:
  caption: ''
  image: ''
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(blogdown)
```


As an early-career researcher, building up a decent publication record can feel like a real battle. By the time you've finished your work and written it up according to your chosen journal's particular specifications, the last thing you might feel like doing is spending more time getting it publication-ready. But if you can still bear to look at it and can afford a small submission delay then creating a video abstract is one way of reaching out to potential readers to capture their attention. In this post I explain the basics of video abstracts and share some of the insights I picked up when I gave it a go. 

### What is a video abstract?

Some journals are starting to suggest creating a "video abstract" to go alongside your paper's text abstract. They're intended to be short (~3 - 5 minutes) and accessible to a wide audience, summing up what the paper is about and the key findings. They might involve video footage of equipment in a lab, narrated slides, simulations, or footage of the author(s) speaking. Many journals don't yet allow video abstracts, so check before you submit if it's something you'd like to do. 

Here's the video abstract I created for the journal IEEE Access in 2019. 

<iframe src="https://www.youtube.com/embed/O8Y_f7TI-h8" width="700" height="394" frameborder="0" style="margin-bottom: 2em;" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>


### What's involved?

I found creating a video abstract to be a bit like making a talk for a conference. However, creating a narrative that can sum up your work and engage a wide audience in just a few minutes is definitely more difficult, and, ironically, more time-consuming. I went with a fairly simple approach: slides with narration enhanced with computer simulations that plays through as a video. It took me a week or two including learning how to make the simulations and record the narration with the slides. 

There are many, far more sophisticated video abstracts out there, but for a first attempt and without any fancy recording equipment, I decided to keep it simple with software I was already familiar with (PowerPoint). I'd argue that even something basic is worth doing if it gets the main points across and adds something to the paper. The worst part is listening back so you can correct when you went wrong/a clock was chiming/sirens went by. 


### Is it really worth doing?

It's hard to tell. Has it increased my citations for this paper? Not (yet) in this instance, but journals make claims such as [_"typically, the most downloaded articles in IEEE Access have video_](http://ieeeaccess.wpengine.com/frequently-asked-questions/), and they highlight a video every fortnight on their main page. The benefits for me were to get better at summing up my work and to learn how to make some cool simulations which I then went on to present at a conference (not ideal as it was a poster presentation, but the poster perusers seemed to really enjoy the unexpected addition of a laptop with simulations). I'd say it's worth doing if:

* the subject lends itself well to a video and might be of interest to those beyond a niche group who are purely interested in the technical details, _or_

* it prompts you to learn a new skill, such as coding simulations, recording an academic video, or using new recording equipment, _or_

* it would be helpful for/helped by an upcoming/recent conference if: 
  + you can use elements of your video in your presentation
  + you can use elements of your presentation in your video
  + you can use the video to advertise your presentation, _and_

* you have a few days to dedicate to the work (note that it is usually needs to be submitted for peer-review with the paper).


### My tips for creating a video abstract

There's a fair bit of advice out there for creating video abstracts (see links below). I recommend:

* Less is more - don't try to say too much or present too many slides

* If you're using slides, keep them simple with images/clips rather than text where possible

* Computer simulations are a great way to enhance what's restricted by the 2D nature of a paper

* Write a script and practice - time is short and it's important to read slowly and clearly, particularly when your audience might not be native speakers

* Choose your software and hardware with your budget and time constraints in mind. PowerPoint might seem pretty basic, but it allowed me to record each slide's audio individually, click through at my own speed, embed simulations, and build on slides and posters I'd made earlier.

Finally, I recommend putting your video on youTube (once it's published) and linking to the paper in the description. I was initially worried about copyright with the journal (check what the rules are) but it's much easier to publicise a youTube video on social media and it's a great way to direct people to the journal's page. I added subtitles to make accessible to a wider audience.  


### If you use PowerPoint

It's not the fanciest or data scienciest software out there, but if you're familiar with it and don't mind everyone knowing you used PowerPoint then it can be a great tool. To create a video from slides with narration:

* Create all your slides and (optionally) write down exactly what you'd like to say for each one 

* Under the _Slide show_ tab, choose from _Rehearse timings_ (to practice and see how long things take) or skip to _Record slide show_ (its arrow)

* After the first time round you might like to start from a later slide (you can record them individually), and clear what you've recorded so far

* A speaker icon appears in the bottom-right-hand corner which allows you to play back your recordings for slides individually (disappears in presenter mode)

* Once you're finished create your .mp4 file by clicking File > Export > Create a video 

* Check the guidelines from the journal about accepted formats and requirements for providing a readme file

* Once your video has been published, upload it to youTube and add subtitles to make it accessible. Add a link to your paper (on the journal's website) in the description. 


### Links

* Journal advice on creating good video abstracts: 
  + [Cell](http://crosstalk.cell.com/blog/6-tips-for-creating-a-video-abstract-anyone-can-enjoy)
  + [BMJ](https://authors.bmj.com/writing-and-formatting/video-abstracts/top-tips/) 
  + [New Journal of Physics](https://iopscience.iop.org/journal/1367-2630/page/How%20to%20make%20a%20good%20video%20abstract)
  
* "Video abstracts, the latest trend in scientific publishing" an [article](https://www.universityaffairs.ca/features/feature-article/video-abstracts-the-latest-trend-in-scientific-publishing/) by Jacob Berkowitz 


_If you have any comments or questions about video abstracts do get in touch!_




